# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dH9eobsgO2IavxKD-mggMh81SU8Sav2n
"""

import matplotlib.pyplot as plt
import numpy as np

x= np.array([0,6])
y= np.array([0,250])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([1,2,3,4,5,6])
y= np.array([1,20,2,18,3,21])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y= np.array([1,200,1.5,189,2,210])

plt.plot(y, marker='*')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y= np.array([1,20,2,18,3,21])

plt.plot(y, 'o:r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y= np.array([1,20,2,18,3,21])

plt.plot(y, marker='o', ms=20)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x1= np.array([1,2,3,4,5,6])
y1= np.array([1,20,2,18,3,21])
x2= np.array([1,2,3,4,5,6])
y2= np.array([22,3,21,1,14,5])

plt.plot(x1,y1,x2,y2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([1,2,3,4,5,6])
y= np.array([1,20,2,18,3,21])

plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([1,2,3,4,5,6])
y= np.array([1,20,2,18,3,21])
plt.scatter(x,y,color='red')

x= np.array([12,20,13,24,15,6])
y= np.array([1,20,2,18,3,21])
plt.scatter(x,y,color='green')

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([1,2,3,4,5,6])
y= np.array([1,20,2,18,3,21])
mycolor=['red', 'green', 'purple', 'lime', 'aqua', 'yellow']
plt.scatter(x,y,color=mycolor)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([1,2,3,4,5,6])
y= np.array([1,20,2,18,3,21])
mycolor=['red', 'green', 'purple', 'lime', 'aqua', 'yellow']
size=[10,60,120,80,20,190]
plt.scatter(x,y,color=mycolor, s=size)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array(['A','B','C','D','E','F'])
y= np.array([1,20,2,18,3,21])

plt.bar(x,y)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array(['A','B','C','D','E','F'])
y= np.array([1,20,2,18,3,21])

plt.barh(x,y)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array(['A','B','C','D','E','F'])
y= np.array([1,20,2,18,3,21])

plt.bar(x,y,width=0.1)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([35,25,15,25])

plt.pie(x)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([35,25,15,25])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
plt.pie(x, labels=mylabels)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([35,25,15,25])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
plt.pie(x, labels=mylabels,startangle=90)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([35,25,15,25])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
myexplode= [0.2,0,0,0]
plt.pie(x, labels=mylabels,startangle=90,explode=myexplode)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([35,25,15,25])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
myexplode= [0.2,0,0,0]
plt.pie(x, labels=mylabels,startangle=90,explode=myexplode, shadow=True)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([35,25,15,25])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
mycolors = ["black", "hotpink", "b", "#4CAF50"]
myexplode= [0.2,0,0,0]
plt.pie(x, labels=mylabels,startangle=90,explode=myexplode, shadow=True, colors=mycolors)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([35,25,15,25])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]

plt.pie(x, labels=mylabels)
plt.legend()
plt.show()